# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='author',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
