# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='i',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
